

SELECT P.PARTY_ID,
       PER.FIRST_NAME,
       PER.LAST_NAME,
       CM.INFO_STRING AS EMAIL,
       TN_PHONE.CONTACT_NUMBER ,
       P.CREATED_DATE AS ENTRY_DATE
FROM PARTY P
         JOIN PARTY_ROLE PR ON P.PARTY_ID = PR.PARTY_ID
         JOIN PERSON PER ON P.PARTY_ID = PER.PARTY_ID
         JOIN PARTY_CONTACT_MECH PCM ON P.PARTY_ID = PCM.PARTY_ID
         JOIN CONTACT_MECH CM ON PCM.CONTACT_MECH_ID = CM.CONTACT_MECH_ID
         JOIN PARTY_CONTACT_MECH PCM_PHONE ON P.party_id = PCM_PHONE.party_id
         JOIN TELECOM_NUMBER TN_PHONE ON PCM_PHONE.contact_mech_id = TN_PHONE.contact_mech_id
WHERE PR.ROLE_TYPE_ID = 'CUSTOMER'
    AND YEAR(P.CREATED_DATE) = 2023
  AND MONTH(P.CREATED_DATE) = 6
  AND CM.CONTACT_MECH_TYPE_ID = 'EMAIL_ADDRESS';